### PR TITLE
libxml2 find

### PR DESCRIPTION
**Pull request by scopatz**
Try this, @FlanFlanagan

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
Error persists. 

`git checkout -b scopatz-xmlfind 0.9
git pull https://github.com/scopatz/Bright-lite.git xmlfind`

**Comment by scopatz** [comment]
Can you post the error please? Thanks!

**Comment by FlanFlanagan** [comment]
`robert@robert-VirtualBox:~/Bright-lite$ python install.py 
/usr/bin/cmake

-- CMAKE_INSTALL_RPATH: /home/robert/.local/lib:/home/robert/.local/lib/cyclus:/usr/lib:/usr/lib/cyclus
CMAKE_MODULE_PATH /share/cmake-2.8/Modules;/home/robert/Bright-lite/cmake
-- Dependency Root Dir (DEPS_ROOT_DIR): /usr
-- Dependency Hints (DEPS_HINTS): HINTS;/usr
-- Dependency Binary Hints (DEPS_BIN_HINTS): HINTS;/usr;/usr/bin
-- Dependency Library Hints (DEPS_LIB_HINTS): HINTS;/usr;/usr/lib
-- Dependency Include Hints (DEPS_INCLUDE_HINTS): HINTS;/usr/include
-- Using /home/robert/.local as CYCLUS_ROOT_DIR.
-- Dependency Cyclus (DEPS_CYCLUS): 
-- Dependency Library Cyclus (DEPS_LIB_CYCLUS): 
-- Dependency Share Cyclus (DEPS_SHARE_CYCLUS): 
-- Dependency Include Cyclus (DEPS_INCLUDE_CYCLUS): 
-- Found Cyclus Core Headers : /home/robert/.local/include/cyclus
-- Found Cyclus Core Test Headers : /home/robert/.local/include/cyclus
-- Found Cyclus Core Shared Data : /home/robert/.local/share/cyclus
-- Found Cyclus Core Library : /home/robert/.local/lib/libcyclus.so
-- Found Cyclus Test Libraries : /home/robert/.local/lib/cyclus/libgtest.so/home/robert/.local/lib/cyclus/libbaseagentunittests.so
CMake Error at CMakeLists.txt:108 (FIND_PACKAGE):
  Could not find a package configuration file provided by "LibXml2" with any
  of the following names:

    LibXml2Config.cmake
    libxml2-config.cmake

  Add the installation prefix of "LibXml2" to CMAKE_PREFIX_PATH or set
  "LibXml2_DIR" to a directory containing one of the above files.  If
  "LibXml2" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/robert/Bright-lite/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "install.py", line 214, in <module>
    main()
  File "install.py", line 211, in main
    install_cyclus(args)
  File "install.py", line 95, in install_cyclus
    shell=(os.name == 'nt'))
  File "/home/robert/miniconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/robert/Bright-lite', '-DCMAKE_INSTALL_PREFIX=/home/robert/.local', '-DDEFAULT_ALLOW_MILPS=FALSE']' returned non-zero exit status 1
`

**Comment by scopatz** [comment]
What version of CMake are you using?

**Comment by FlanFlanagan** [comment]
3.5.1

**Comment by scopatz** [comment]
hmm peculiar, can you find LibXml2Config.cmake or libxml2-config.cmake on your file system?

**Comment by scopatz** [comment]
Do you have libxml2 and/or libxml2-dev installed?

**Comment by FlanFlanagan** [comment]
Yes, libxml2-dev

**Comment by scopatz** [comment]
But do those files exist anywhere?

**Comment by FlanFlanagan** [comment]
Yes they did exist. 

I fixed the issue by conda installing libxml2. 

`CMake Error at /home/robert/.local/share/cyclus/cmake/FindHDF5.cmake:170 (message):
  "HL" is not a valid HDF5 component.
Call Stack (most recent call first):
  CMakeLists.txt:151 (FIND_PACKAGE)
`

**Comment by scopatz** [comment]
Interesting, I guess you are mixing system installs and conda installed.  For the HDF5 issue, delete the file `/home/robert/.local/share/cyclus/cmake/FindHDF5.cmake`. It should no longer exist because we now rely on the FindHDF5.cmake that is distributed with cmake, rather than cyclus' home grown one.

**Comment by FlanFlanagan** [comment]
Yeah, my VM is an installation mess. Thanks for the help!

Up to your error now. Thanks. Going to merge in this fix.

**Pull request merged**
