### PR TITLE
PCRE and Python build improvements

### PR DESCRIPTION
**Pull request by scopatz**
Here are some more build system improvements I needed

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
What build issue is this fixing?

**Comment by scopatz** [comment]
Ones where you building totally based on conda and no system libraries

**Comment by FlanFlanagan** [comment]
I had libxml2-dev installed using apt-get it just wasn't finding it. Not sure what was the cause.

**Comment by scopatz** [comment]
Yeah, but this is for pcre and Python, not libxml

**Pull request merged**
